# # CD workflow for React app on GH Pages
# name: React App CD

# on:
#   push:
#     branches:
#     - master
#   workflow_dispatch:
# jobs:
#   deploy-staging:
#     name: Deploy to staging environment
#     runs-on: ubuntu-latest
#     environment: Staging
#     steps:
#       - name: Checkout 
#         uses: actions/checkout@v2
#       - name: Install and Build
#         run: |
#           npm install
#           npm run build:staging
#       - name: Deploy 
#         uses: JamesIves/github-pages-deploy-action@4.1.5
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: build
#           token: ${{secrets.REPO_PUSH_TOKEN}}